version: '3'

services:
  # 默认模式 (stdio) - 适用于本地客户端连接
  minimax-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MINIMAX_API_KEY=${MINIMAX_API_KEY}  # 从环境变量获取
      - MINIMAX_API_HOST=${MINIMAX_API_HOST:-https://api.minimax.chat}  # 默认使用国内版API
      - MINIMAX_API_RESOURCE_MODE=${MINIMAX_API_RESOURCE_MODE:-url}  # 默认使用URL模式
    volumes:
      - ./data:/data  # 将本地data目录挂载到容器的/data目录
    restart: unless-stopped

  # SSE模式 - 适用于网络客户端连接
  minimax-mcp-sse:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MINIMAX_API_KEY=${MINIMAX_API_KEY}  # 从环境变量获取
      - MINIMAX_API_HOST=${MINIMAX_API_HOST:-https://api.minimax.chat}  # 默认使用国内版API
      - MINIMAX_API_RESOURCE_MODE=${MINIMAX_API_RESOURCE_MODE:-url}  # 默认使用URL模式
    volumes:
      - ./data:/data  # 将本地data目录挂载到容器的/data目录
    ports:
      - "8000:8000"  # 将容器内的8000端口映射到主机的8000端口
    command: --sse --host 0.0.0.0 --port 8000
    restart: unless-stopped

# 使用说明:
# 1. 创建.env文件并添加必要的环境变量:
#    MINIMAX_API_KEY=your_api_key
#    MINIMAX_API_HOST=https://api.minimax.chat  # 国内版API
#    # 或 MINIMAX_API_HOST=https://api.minimaxi.chat  # 国际版API
#    MINIMAX_API_RESOURCE_MODE=url  # 或 local
#
# 2. 启动所有服务:
#    docker-compose up -d
#
# 3. 仅启动stdio模式:
#    docker-compose up -d minimax-mcp
#
# 4. 仅启动SSE模式:
#    docker-compose up -d minimax-mcp-sse
#
# 5. 查看日志:
#    docker-compose logs -f 